CREATE TABLE MOVIE (
ID NUMBER,
CONSTRAINT M_ID PRIMARY KEY (ID),
TITLE VARCHAR2(50) NOT NULL UNIQUE,
DIRECTOR VARCHAR2(50) NOT NULL,
YEAR NUMBER(4) CHECK(YEAR BETWEEN 1900 AND 2018),
LENGTH_MIN NUMBER(3) CHECK(LENGTH_MIN BETWEEN 10 AND 200)
);