https://www.gromcode.com/task1843
1 -
SELECT COUNT(ID), DIRECTOR FROM MOVIE GROUP BY DIRECTOR;

2 -

SELECT MOVIE.DIRECTOR, SUM(MOVIE_STAT.DOMESTIC_SALES), SUM(MOVIE_STAT.INTERNATIONAL_SALES)
FROM MOVIE, MOVIE_STAT
WHERE MOVIE.ID = MOVIE_STAT.MOVIE_ID
GROUP BY MOVIE.DIRECTOR;


SELECT MOVIE.DIRECTOR, SUM(MOVIE_STAT.DOMESTIC_SALES), SUM(MOVIE_STAT.INTERNATIONAL_SALES), COUNT(MOVIE_STAT.MOVIE_ID)
FROM MOVIE
INNER JOIN MOVIE_STAT ON MOVIE_STAT.MOVIE_ID = MOVIE.ID
GROUP BY MOVIE.DIRECTOR;


https://www.gromcode.com/task1844
1 -
SELECT * FROM MOVIE ORDER BY YEAR DESC;

2 -
SELECT * FROM MOVIE_STAT ORDER BY INTERNATIONAL_SALES DESC;