CREATE TABLE PRODUCTS (
 ID NUMBER,
 CONSTRAINT PRODUCT_ID PRIMARY KEY(ID),
 ProductName VARCHAR2(200) NOT NULL,
 SUPPLIER_ID NUMBER,
 CONSTRAINT SUPPLIER_FK FOREIGN KEY (SUPPLIER_ID)
 REFERENCES SUPPLIERS(ID),
 CATEGORY_ID NUMBER,
 CONSTRAINT CATEGORY_FK FOREIGN KEY (CAT_ID)
 REFERENCES CATEGORIES(ID),
 QuantityPerUnit NUMBER,
 UnitPrice NUMBER(*,2),
 UnitsInStock NUMBER,
 UnitsOnOrder NUMBER,
 ReorderedLevel NUMBER,
 Discontinued NUMBER
);
