CREATE TABLE FORUMSUBCATEGORIES (
ID NUMBER,
CONSTRAINT FCATEGORY_ID PRIMARY KEY (ID),
ID_CATEGORY NUMBER,
CONSTRAINT FCATEGORY_FK FOREIGN KEY (ID_CATEGORY) REFERENCES FORUMCATEGORIES(ID),
TITLE VARCHAR2(64),
DESCRIPTION VARCHAR2(200),
CAT_DATE DATE,
IP VARCHAR2(20)
);