CREATE TABLE FORUMPOLLSOPTIONSVOTES (
ID NUMBER,
CONSTRAINT VOTE_ID PRIMARY KEY (ID),
ID_POLLOPTION NUMBER,
CONSTRAINT POLLOPTION_FK FOREIGN KEY(ID_POLLOPTION) REFERENCES FORUMPOLLSOPTIONS(ID),
ID_USER NUMBER,
CONSTRAINT USER_ID_FK FOREIGN KEY(ID_USER) REFERENCES USERS(ID),
VOTE_DATE DATE,
IP VARCHAR2(20)
);