SELECT SALESMAN.NAME, CUSTOMER.CUSTNAME
FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID;

SELECT SALESMAN.NAME, CUSTOMER.CUSTNAME, SALESMAN.CITY
FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.CITY = CUSTOMER.CITY;

SELECT SALESMAN.NAME, CUSTOMER.CUSTNAME, SALESMAN.CITY
FROM SALESMAN, CUSTOMER
WHERE SALESMAN.CITY = CUSTOMER.CITY;

SELECT CUSTOMER.CUSTNAME, CUSTOMER.CITY, SALESMAN.NAME, SALESMAN.CITY,
FROM SALESMAN,
JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID AND DEAL ON DEAL.CUSTOMER_ID == CUSTOMER.CUSTOMER_ID AND DEAL.AMOUNT > 10000;


SELECT CUSTOMER.CUSTNAME, CUSTOMER.CITY, SALESMAN.NAME, SALESMAN.CITY
FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
JOIN DEAL ON DEAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
WHERE DEAL.AMOUNT > 10000;

SELECT CUSTOMER.CUSTNAME
FROM CUSTOMER
JOIN DEAL ON DEAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
WHERE DEAL.DDATE >= '01.01.2017' AND DEAL.DDATE < '01.01.2019';

SELECT SALESMAN.NAME, SUM (DEAL.AMOUNT)
FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
JOIN DEAL ON DEAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
WHERE DEAL.DDATE >= '01.08.2017' AND DEAL.DDATE < '01.09.2017';


-- 1st case
SELECT s_name, sales_sum
FROM
(SELECT SALESMAN.NAME AS s_name, SUM(DEAL.AMOUNT) AS sales_sum
FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
JOIN DEAL ON DEAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
WHERE DEAL.DDATE >= '01.08.2017' AND DEAL.DDATE < '01.08.2017'
GROUP BY SALESMAN.NAME)
WHERE sales_sum =
(SELECT MAX(sales_sum) FROM
(SELECT SALESMAN.NAME AS s_name, SUM(DEAL.AMOUNT) AS sales_sum
FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
JOIN DEAL ON DEAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
WHERE DEAL.DDATE >= '01.08.2017' AND DEAL.DDATE < '01.08.2017'
GROUP BY SALESMAN.NAME));


--- OR 2nd case
SELECT s_name
FROM
(SELECT SALESMAN.NAME AS s_name, SUM(DEAL.AMOUNT) AS sales_sum,
FIRST_VALUE (SUM(DEAL.AMOUNT)) OVER (ORDER BY SUM(DEAL.AMOUNT) DESC) AS maxs
FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
JOIN DEAL ON DEAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
WHERE DEAL.DDATE >= '01.08.2017' AND DEAL.DDATE < '01.08.2017'
GROUP BY SALESMAN.NAME)
WHERE sales_sum = maxs;

-- OR 3rd case
WITH sumTable AS
(SELECT SALESMAN.NAME AS s_name, SUM(DEAL.AMOUNT) AS sales_sum
FROM SALESMAN
JOIN CUSTOMER ON SALESMAN.SALESMAN_ID = CUSTOMER.SALESMAN_ID
JOIN DEAL ON DEAL.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
WHERE DEAL.DDATE >= '01.08.2017' AND DEAL.DDATE < '01.08.2017'
GROUP BY SALESMAN.NAME
ORDER BY sales_sum DESC)
SELECT s_name
FROM sumTable
WHERE sales_sum = (SELECT sales_sum FROM sumTable WHERE ROWNUM = 1);
